### ISSUE TITLE
How can I add the oid type column?

### ISSUE THREAD

**Issue by yasirs** [diogob/carrierwave-postgresql#1]
According to the Readme, we need to have the oid column:

```
add_column :users, :avatar, :oid
```

I have a migration that looks like

```
class CreateUploadedFiles < ActiveRecord::Migration
  def change
    create_table :uploaded_files do |t|
      t.oid :file_oid
      t.string :type
      t.bool :processed

      t.timestamps
    end
  end
end
```

But `oid` is not recognized and rake migration gives me an error:

```
undefined method `oid' for <ActiveRecord::ConnectionAdapters::PostgreSQLAdapter::TableDefinition:0x00000005bd0c18>
```

**Comment by iamtoc** [comment]
Having the same issue when migrating database:
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:
undefined method `oid' for #<ActiveRecord::ConnectionAdapters::PostgreSQL::TableDefinition:0x007fae46f44a88>

Any clues how to resolve this? Thanks!
