### ISSUE TITLE
JDBC Support

### ISSUE THREAD

**Issue by TheKidCoder** [diogob/carrierwave-postgresql#14]
Are there any plans to support the Postgres JDBC driver? I can give a stab at it, but would like to know first if anyone has tried it/planning on it.

**Comment by TheKidCoder** [comment]
@nadavshatz Just a heads up, JDBC has been merged in and is in v. 0.2.0.

Closing this.

**Comment by nadavshatz** [comment]
Thanks for the update @TheKidCoder :beers:
