### ISSUE TITLE
undefined method `lo_creat'

### ISSUE THREAD

**Issue by manish-thinkbridge** [diogob/carrierwave-postgresql#25]
Hi All,
I want to integrate 'carrierwave-postgresql' in my project. I was using carrierwave earlier for uploading images to file system, which was working fine. Now I want to store the images in PostgreSQL db.
I've followed the readme.
Added this in uploader:
```
storage :postgresql_lo
```

and commented out this:
```
# storage :file
..
..
..
# def store_dir
    # "images/#{model.class.to_s.underscore}/#{mounted_as}/#{model.id}"
# end
```
Changed the datatype of existing column to oid (mounted my uploaders previously).

But when I try to upload the image it gives me this error:
```
undefined method `lo_creat' for #<ActiveRecord::ConnectionAdapters::PostgreSQLJdbcConnection:0x50ea6809>
```

What am I doing wrong ? :(

**Comment by diogob** [comment]
Currently there is no JDBC support. This gem only works with the pg gem.
There is an old PR that integrates JDBC but it was never merged. It could be with some work: https://github.com/diogob/carrierwave-postgresql/pull/18
