### ISSUE TITLE
Bump carrierwave dependency version?

### ISSUE THREAD

**Issue by vinc** [diogob/carrierwave-postgresql#32]
Hi,

I'm using `carrierwave-postgresql` version `0.1.5` with `carrierwave` version `1.2.2` and I'd like to use the last version `0.2.0` of this gem but it sets a dependency on an earlier version of `carrierwave` (~> 0.10.0).

Is it safe for everyone to bump this dependency version?

P.S. thanks for this gem <3

**Comment by diogob** [comment]
Hi there, I have just pushed the version 0.3.0 that should fix the issue.
Let me know if you find further problems.
